<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>ml_itp</RootNamespace>
    <Authors>SDraw</Authors>
    <Platforms>x64</Platforms>
    <Product>IndexTrackpadParams</Product>
    <PackageId>IndexTrackpadParams</PackageId>
    <AssemblyName>IndexTrackpadParams</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>embedded</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(CVRPath)/ChilloutVR_Data/Managed/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>$(CVRPath)/MelonLoader/net35/MelonLoader.dll</HintPath>
      <Private>false</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
    <Reference Include="SteamVR">
      <HintPath>$(CVRPath)/ChilloutVR_Data/Managed/SteamVR.dll</HintPath>
      <Private>false</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(CVRPath)/ChilloutVR_Data/Managed/UnityEngine.AnimationModule.dll</HintPath>
      <Private>false</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(CVRPath)/ChilloutVR_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
    <Reference Include="VRBinding">
      <HintPath>$(CVRPath)/Mods/VRBinding.dll</HintPath>
      <Private>false</Private>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /y &quot;$(TargetPath)&quot; &quot;$(CVRPath)/Mods/&quot;" />
  </Target>

</Project>
